= Welcome

Ost Platform is built on https://openst.org/[OpenST Protocol] and OpenST Mosaic. Together, these allow for the creation of value-backed tokens on scalable side-chains on Etheruem, and finalizing thousands of transactions per second asynchronously to Ethereum at low cost.

Ost Server APIs and SDKs provide various endpoints/methods that can be used by developers to design and manage their Token Economies. Ost Client (Mobile Wallet) SDKs enable end-users to safely interact with tokens.

== What Can I do with Ost Platform?

* Launch your own token
* Run hundreds of thousands of transactions on Ost scalable side-chains
* Embed a self-custodial Ethereum wallet into your application(s)
* Attach value to user actions -- be it an upvote, a like, a store visit, a contribution, or a 5-star review
* Process microtransactions: high volume, low value transfers at near-zero cost

== Why Ost Platform?

. Designed to provide everything you need to deploy tokens to drive engagement.

. Designed with mainstream users in mind. Your users won't even know it's crypto.

. Designed for internet-grade transaction volumes and speeds at near-zero cost

. Developer friendly: Ost SDKs enable a fast and painless integration into your applcation(s) without requiring in-house blockchain expertise -- so you can focus on your business and leave the blockchain bits to us.

== Tools

All the open source tools built and maintained by the Ost team:

[.card.card-primary.card-starter-kits]
--
xref:quick-start-guides:index.adoc[[.card-title]#Quick Start Guides# [.card-body]#Quick Start Guides For Developers!# [.card-cta]#Get Started >#]
--

[.card.card-primary.card-sdk]
--
xref:server-sdks:index.adoc[[.card-title]#Server SDKs# [.card-body]#A guide to Ost Server SDKs# [.card-cta]#Get started >#]
--

[.card.card-primary.card-sdk]
--
xref:client-sdks:index.adoc[[.card-title]#Client SDKs# [.card-body]#A guide to Ost Client SDKs# [.card-cta]#Get started >#]
--

[.card.card-primary.card-sdk]
--
xref:browser-sdks:index.adoc[[.card-title]#Browser SDKs# [.card-body]#A guide to Ost Browser SDKs# [.card-cta]#Get started >#]
--

== Learn

Comprehensive guides to Ost.

include::learn::partial$cards.adoc[]

=== Additional topics to be included

* Sandbox environment
* User interface (UI) components
* Custom Rules Framework
* APIs
* Webhooks
* Block Explorer


== More from Ost

=== Audits

Abc


=== Careers

Abc

=== Social

Abc

== Questions?

Abc

== Share the Love!

Abc


// ```markdown
// [![built-with openzeppelin](https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF)](https://docs.openzeppelin.com/)
// ```