= Metacartel Hackathon (March-2020)

For Metacartel Hackathon, Ost is interested in teams building with the Ost React Native Client (mobile wallet) SDK and / or the *new Ost Browswer wallet SDK.* In each case, a full server-side integration should be done.

To facilitate 'browser-first' projects, Ost is making available a starter wallet app that can be configured to work with your layer-2 token.

== Get Started
. Set-up token and do stake and mint
. Retrieve API keys and implement authentication
. Optional: Check-out the Ost demo server application
. Set-up own app server and user auth service and integrate the Ost Server SDK

NOTE: At this point, you should be able to retrieve token details and rule addresses, create your end-users in Ost Platform, and create an (encrypted) salt for each user. 

=== Mobile App Projects
. Build your app product and integrate the Ost React Native Client SDK
. Optional: Check-out the Ost React Native Wallet App

=== Browser Projects
. Clone the Ost React Native Wallet App and and configure
. Build your web product and integrate the Ost Browser wallet SDK!

== We're here to help!
Connect with Ost developers and the community at larger in the
https://email.ost.com/t?entity_type=2&entity_id=27311&email_pref_id=44821608&sent_id=1579614932&service_id=22436&redirect_url=https%3A%2F%2Fjoin.slack.com%2Ft%2Ftryost%2Fshared_invite%2FenQtNjk5MTI4NDY5MjIyLTFlZWYyODNhMjA0YmNmM2ZmMTJkZDM4MDU0NGJlNDc3ZWEwMjY5ZWNiNjNiZDcyOTIyZTljNGFmN2E2NzY2MDk[Ost Public Slack space]