= High-Level Understanding of Ost SDKs

To integrate with Ost Platform you must integrate both Ost server SDK and Ost client (mobile wallet) SDK into your application(s).

This page describes the actions that can be performed and how you would go about retrieving your token details, registering users, and setting-up users with a wallet so that they can hold and interact with tokens (sign, send, receieve).

== Actions Enabled Through SDKs

=== Server SDK

. Get token information (/token object)
 ** Pass token id
. Register user: Ost Platform will respond with user entity. Once users is registered, generate `passphrasePrefix` for the user. This will be used during the client SDK `activateUser` workflow.
 ** Pass token id and user id
. When activate user is called (via client SDK), then register device if not already registered
 ** Once called, your mobile app must send device details to your server
 ** Your server then creates device on Ost Platform for user
  *** Ost Platform returns device entity to your server
  *** Your server returns device entity to your mobile app
  *** Your mobile app calls `deviceRegistered` callback (with device entity)
  *** Client SDK syncs user details with Ost Platform
  *** Client SDK calls `flowComplete` callback


=== Client SDK

. Call `setupDevice` workflow
 ** Calls `registerDevice` (sever SDK) if device key is not registerd with Ost Platform, else flowComplete
. Call `activateUser` workflow
 ** First, ask user to set wallet PIN and retrieve `passphrasePrefix` for user from your server
 ** Client SDK creates session keys and recovery owner key
 ** Your app calls `activateUser` with (PIN, passphrasePrefix, sessionKey details)
 ** Client SDK sends device key, session key, recovery owner key to Ost Platform
 ** Ost Platform deploys smart contracts for user: tokenHolder, deviceManager (multisig) and activates the user
. Create `sessionKeys`
. Create `recoveryOwnerKey`


=== Set-up Steps and Contracts Deployed

[cols="1,4", options="header"]
|===
|Step
|Description

|Token
|Ost writes and deploys the TokenRules contract for the Company and writes a PricerRule contract and registers the rule with the TokenRules contract on the auxiliary sidechain.

|User
|When an end-user registers on a client app a TokenHolder contract and a DeviceManager (MultiSig) contract are created and deployed by the client via Ost Platform APIs/SDKs.

|User Wallet
|Activating a user wallet involves the deployment and registration of the following contracts: TokenHolder, MultiSig, DelayedRecoveryModule

|Execute Transaction
|Users can spend tokens by signing transactions using private keys on their registered mobile device.
|===